### ISSUE TITLE
Installing?

### ISSUE THREAD

**Issue by veeshy** [INTO-CPS-Association/fmu-builder#3]
Does this work under ubuntu 18.04? Performing the cmake command on the readme.md and got: 

```
CMake Error at CMakeLists.txt:43 (string):
  string sub-command REPLACE requires at least four arguments.


-- srcs: 
CMake Error at CMakeLists.txt:46 (PREPEND):
  PREPEND Function invoked with incorrect arguments for function named:
  PREPEND


-- Prepended srcs: 
You have called ADD_LIBRARY for library C without any source files. This typically indicates a problem with your CMakeLists.txt file
```
once installed, do you simply provide the FMU path to the compile-fmu.sh script?

**Comment by CThuleHansen** [comment]
It should work under ubuntu 18.04,
and yes, you should provide the FMU path to compile-fmu.sh. Otherwise it is available here: https://sweng.au.dk/fmubuilder/

**Comment by veeshy** [comment]
Hm, okay I'll try harder on the local install of the script.

I tried running my FMU through that online tool originally and ran into errors
[fmubuilder_online_error.txt](https://github.com/INTO-CPS-Association/fmu-builder/files/2295471/fmubuilder_online_error.txt). I used open modelica to generate an FMU using a modelica example (modelica.fluids.examples.onemass), but can't attach the fmu generated here. It was generated for model exchange 2.0.

**Comment by CThuleHansen** [comment]
Hi veeshy, so far we only support FMI for co-simulation.
Can you send the FMU to casper.thule@eng.au.dk?

**Comment by veeshy** [comment]
Ohh! Yup, that would be the issue, darn. Still a cool tool you have here! I'll send the ME FMU to that address too and mark this as closed. Thanks for the info!

**Comment by CThuleHansen** [comment]
Hi @veeshy,
If you are still trying locally, then some of the lines that needs to be fixed are:
https://github.com/INTO-CPS-Association/fmu-builder/blob/master/fmu-compiler/compile-fmu.sh#L190 (Looks for the co-simulation tag in the modeldescription file)
https://github.com/INTO-CPS-Association/fmu-builder/blob/master/fmu-compiler/compile-fmu.sh#L198 looks for source files within co-simulation tag within model description file according to p 67 of FMI std (https://svn.modelica.org/fmi/branches/public/specifications/v2.0/FMI_for_ModelExchange_and_CoSimulation_v2.0.pdf).

I guess the other stuff could work for modelexchange as well
