### ISSUE TITLE
`strdup` not found when building FMU generated with OpenModelica 1.19.2

### ISSUE THREAD

**Issue by rudi** [INTO-CPS-Association/fmu-builder#4]
Hi, I'm trying to add Windows and Mac support for an FMU created by OpenModelica 1.19.2 on Linux.  When uploading the FMU to https://sweng.au.dk/fmubuilder, the build ends with the following message:

```
[ 36%] Building C object CMakeFiles/Linear.dir/sources/gc/memory_pool.c.o
/usr/bin/cc -DLinear_EXPORTS -I/tmp/fmu.folT0nA0p5/build/linux64 -I/tmp/fmu.folT0nA0p5 -I/tmp/fmu.folT0nA0p5/sources -I/home/fmubuilder/fmu-builder/fmu-compiler/includes/fmi -fmessage-length=0 -std=c11 -fPIC -o CMakeFiles/Linear.dir/sources/gc/memory_pool.c.o -c /tmp/fmu.folT0nA0p5/sources/gc/memory_pool.c
/tmp/fmu.folT0nA0p5/sources/gc/memory_pool.c:181:3: error: 'strdup' undeclared here (not in a function)
strdup,
^
CMakeFiles/Linear.dir/build.make:617: recipe for target 'CMakeFiles/Linear.dir/sources/gc/memory_pool.c.o' failed
```

The model is as follows: (Would upload, but github doesn't allow `.mo` files)

```openmodelica
model Linear 
  input Integer inPort;
  output Integer outPort;
  output Integer leak;

  protected Real level;
equation 
  der(level) = inPort;
  leak = max(0, level - 50);
  outPort = integer(level);
end Linear;
```

I remember seeing the error with other FMUs generated by Modelinca as well; apologies for not filing a bug earlier.

**Comment by rudi** [comment]
[Linear.fmu.zip](https://github.com/INTO-CPS-Association/fmu-builder/files/9093677/Linear.fmu.zip)

Here is the fmu that was generated by openmodelica 1.19.2 / Linux for the above file; I had to add a `.zip` extension to make github happy but otherwise it's unchanged.

**Comment by rudi** [comment]
This seems to be a bug in OpenModelica -- directly building an FMU via `omc` on macOS results in similar compilation errors, so I'll go ahead and close the bug.

**Comment by clagms** [comment]
Thanks Rudolf! We are trying to find resources to improve nevertheless, so
your feedback is very much welcome!
